package Kasa;

import javax.swing.JFrame;

/**
 *
 * @author Amar Musli, 2017/210017 - Fakultet za računarstvo i informatiku, Univerzitet Sinergija, Bijeljina.
 */
public class nisiAdministratorProzor extends javax.swing.JFrame {

    /**
     * Creates new form neuspjesnaPrijavaProzor
     */
    public nisiAdministratorProzor() {
        initComponents();
        JFrame nisiAdministratorProzor = new JFrame();
        setLocationRelativeTo(null);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Kasa/slike/prijava.png")).getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        glavniPanel = new javax.swing.JPanel();
        ovomDijeluTekst = new javax.swing.JLabel();
        ureduDugme = new javax.swing.JButton();
        neuspjesnaPrijavaTekst1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nije uspjelo!");
        setName("Nije uspjelo!"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(520, 225));
        setResizable(false);
        setSize(new java.awt.Dimension(520, 225));

        glavniPanel.setBackground(new java.awt.Color(27, 88, 138));
        glavniPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 120, 189), 6));
        glavniPanel.setToolTipText(null);
        glavniPanel.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        glavniPanel.setName("Nije uspjelo!"); // NOI18N

        ovomDijeluTekst.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        ovomDijeluTekst.setForeground(new java.awt.Color(224, 220, 211));
        ovomDijeluTekst.setText("ne možete pristupiti ovom dijelu");
        ovomDijeluTekst.setToolTipText(null);
        ovomDijeluTekst.setName("Nije uspjelo!"); // NOI18N

        ureduDugme.setBackground(new java.awt.Color(27, 88, 138));
        ureduDugme.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        ureduDugme.setForeground(new java.awt.Color(224, 220, 211));
        ureduDugme.setText("  U redu  ");
        ureduDugme.setToolTipText(null);
        ureduDugme.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 220, 211), 3, true));
        ureduDugme.setName("U redu"); // NOI18N
        ureduDugme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ureduDugmeActionPerformed(evt);
            }
        });

        neuspjesnaPrijavaTekst1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        neuspjesnaPrijavaTekst1.setForeground(new java.awt.Color(224, 220, 211));
        neuspjesnaPrijavaTekst1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kasa/slike/obrisi.png"))); // NOI18N
        neuspjesnaPrijavaTekst1.setText("Niste administrator kase tako da");
        neuspjesnaPrijavaTekst1.setToolTipText(null);
        neuspjesnaPrijavaTekst1.setName("Nije uspjelo!"); // NOI18N

        javax.swing.GroupLayout glavniPanelLayout = new javax.swing.GroupLayout(glavniPanel);
        glavniPanel.setLayout(glavniPanelLayout);
        glavniPanelLayout.setHorizontalGroup(
            glavniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(glavniPanelLayout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(glavniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, glavniPanelLayout.createSequentialGroup()
                        .addGroup(glavniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(neuspjesnaPrijavaTekst1)
                            .addComponent(ovomDijeluTekst))
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, glavniPanelLayout.createSequentialGroup()
                        .addComponent(ureduDugme, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(196, 196, 196))))
        );
        glavniPanelLayout.setVerticalGroup(
            glavniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(glavniPanelLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(neuspjesnaPrijavaTekst1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ovomDijeluTekst)
                .addGap(36, 36, 36)
                .addComponent(ureduDugme, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        ovomDijeluTekst.getAccessibleContext().setAccessibleDescription("Nije uspjelo!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(glavniPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(glavniPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        glavniPanel.getAccessibleContext().setAccessibleName("Nije uspjelo!");
        glavniPanel.getAccessibleContext().setAccessibleDescription("Nije uspjelo!");

        getAccessibleContext().setAccessibleDescription("Nije uspjelo!");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ureduDugmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ureduDugmeActionPerformed

        this.dispose();

    }//GEN-LAST:event_ureduDugmeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nisiAdministratorProzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nisiAdministratorProzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nisiAdministratorProzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nisiAdministratorProzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nisiAdministratorProzor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel glavniPanel;
    private javax.swing.JLabel neuspjesnaPrijavaTekst1;
    private javax.swing.JLabel ovomDijeluTekst;
    private javax.swing.JButton ureduDugme;
    // End of variables declaration//GEN-END:variables
}
