package Kasa;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.JFrame;

/**
 *
 * @author Amar Musli, 2017/210017 - Fakultet za računarstvo i informatiku, Univerzitet Sinergija, Bijeljina.
 */
public class Prijava extends javax.swing.JFrame {
    
   static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
   static final String server_databaze = "jdbc:mysql://192.168.10.16:3306/java"; 
   static final String korisnik_databaze = "student";
   static final String sifra_databaze = "student";

    /**
     * Creates new form Prijava
     */
    public Prijava() {
        initComponents();
        JFrame prijava = new JFrame();
        setLocationRelativeTo(null);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Kasa/slike/prijava.png")).getImage());
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        glavniPanel = new javax.swing.JPanel();
        unosImena_unos = new javax.swing.JTextField();
        unosSifre_unos = new javax.swing.JPasswordField();
        smjenaTekst = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        smjena_unos = new javax.swing.JComboBox<>();
        prijavaTekst = new javax.swing.JLabel();
        upisImenaTekst = new javax.swing.JLabel();
        upisSifreTekst = new javax.swing.JLabel();
        prijaviSe_dugme = new javax.swing.JButton();
        resetujPolja_dugme = new javax.swing.JButton();
        razdvaja = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Caffe bar \"Romansa\" - Prijava");
        setBackground(new java.awt.Color(27, 88, 138));
        setName("Caffe bar \"Romansa\" - Prijava"); // NOI18N
        setPreferredSize(new java.awt.Dimension(902, 756));
        setResizable(false);
        setSize(new java.awt.Dimension(902, 756));

        glavniPanel.setBackground(new java.awt.Color(27, 88, 138));
        glavniPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 120, 189), 3, true));
        glavniPanel.setForeground(new java.awt.Color(164, 214, 146));
        glavniPanel.setToolTipText(null);
        glavniPanel.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        glavniPanel.setPreferredSize(new java.awt.Dimension(896, 727));

        unosImena_unos.setBackground(new java.awt.Color(27, 68, 115));
        unosImena_unos.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        unosImena_unos.setForeground(new java.awt.Color(224, 220, 211));
        unosImena_unos.setToolTipText(null);
        unosImena_unos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        unosSifre_unos.setBackground(new java.awt.Color(27, 68, 115));
        unosSifre_unos.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        unosSifre_unos.setForeground(new java.awt.Color(224, 220, 211));
        unosSifre_unos.setToolTipText(null);
        unosSifre_unos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        unosSifre_unos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unosSifre_unosActionPerformed(evt);
            }
        });

        smjenaTekst.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        smjenaTekst.setForeground(new java.awt.Color(224, 220, 211));
        smjenaTekst.setText("Smjena:");
        smjenaTekst.setToolTipText(null);
        smjenaTekst.setName("Smjena:"); // NOI18N

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kasa/slike/logo.png"))); // NOI18N
        logo.setToolTipText(null);
        logo.setName("Logo"); // NOI18N

        smjena_unos.setBackground(new java.awt.Color(27, 68, 115));
        smjena_unos.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        smjena_unos.setForeground(new java.awt.Color(224, 220, 211));
        smjena_unos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prva", "Druga" }));
        smjena_unos.setToolTipText(null);
        smjena_unos.setName("Izaberite smjenu"); // NOI18N

        prijavaTekst.setBackground(new java.awt.Color(224, 220, 211));
        prijavaTekst.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        prijavaTekst.setForeground(new java.awt.Color(224, 220, 211));
        prijavaTekst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kasa/slike/kasa.png"))); // NOI18N
        prijavaTekst.setText("Caffe bar \"Romansa\" - Prijava");
        prijavaTekst.setToolTipText(null);
        prijavaTekst.setName("Caffe bar \"Romansa\" - Prijava"); // NOI18N

        upisImenaTekst.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        upisImenaTekst.setForeground(new java.awt.Color(224, 220, 211));
        upisImenaTekst.setText("Upišite vaše ime:");
        upisImenaTekst.setToolTipText(null);
        upisImenaTekst.setName("Upišite vaše ime"); // NOI18N

        upisSifreTekst.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        upisSifreTekst.setForeground(new java.awt.Color(224, 220, 211));
        upisSifreTekst.setText("Upišite vašu šifru:");
        upisSifreTekst.setToolTipText(null);
        upisSifreTekst.setName("Upišite vašu šifru"); // NOI18N

        prijaviSe_dugme.setBackground(new java.awt.Color(27, 88, 138));
        prijaviSe_dugme.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        prijaviSe_dugme.setForeground(new java.awt.Color(224, 220, 211));
        prijaviSe_dugme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kasa/slike/prijava.png"))); // NOI18N
        prijaviSe_dugme.setText("Prijavi se u sistem");
        prijaviSe_dugme.setToolTipText(null);
        prijaviSe_dugme.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 220, 211), 3, true));
        prijaviSe_dugme.setName("Prijavi se u sistem"); // NOI18N
        prijaviSe_dugme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prijaviSe_dugmeActionPerformed(evt);
            }
        });

        resetujPolja_dugme.setBackground(new java.awt.Color(27, 88, 138));
        resetujPolja_dugme.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        resetujPolja_dugme.setForeground(new java.awt.Color(224, 220, 211));
        resetujPolja_dugme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kasa/slike/reset.png"))); // NOI18N
        resetujPolja_dugme.setText("Očisti polja");
        resetujPolja_dugme.setToolTipText(null);
        resetujPolja_dugme.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 220, 211), 3, true));
        resetujPolja_dugme.setName("Očisti polja"); // NOI18N
        resetujPolja_dugme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetujPolja_dugmeActionPerformed(evt);
            }
        });

        razdvaja.setBackground(new java.awt.Color(36, 120, 189));
        razdvaja.setForeground(new java.awt.Color(170, 161, 136));
        razdvaja.setOrientation(javax.swing.SwingConstants.VERTICAL);
        razdvaja.setToolTipText(null);
        razdvaja.setName("Razdvaja"); // NOI18N

        javax.swing.GroupLayout glavniPanelLayout = new javax.swing.GroupLayout(glavniPanel);
        glavniPanel.setLayout(glavniPanelLayout);
        glavniPanelLayout.setHorizontalGroup(
            glavniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, glavniPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(prijavaTekst)
                .addGap(126, 126, 126))
            .addGroup(glavniPanelLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(glavniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(glavniPanelLayout.createSequentialGroup()
                        .addComponent(logo)
                        .addGap(147, 147, 147)
                        .addGroup(glavniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(upisSifreTekst)
                            .addComponent(smjenaTekst)
                            .addComponent(upisImenaTekst))
                        .addGap(56, 56, 56)
                        .addGroup(glavniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unosImena_unos, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(smjena_unos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unosSifre_unos, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(glavniPanelLayout.createSequentialGroup()
                        .addComponent(prijaviSe_dugme, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(resetujPolja_dugme, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(133, Short.MAX_VALUE))
            .addGroup(glavniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(glavniPanelLayout.createSequentialGroup()
                    .addGap(367, 367, 367)
                    .addComponent(razdvaja, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(511, Short.MAX_VALUE)))
        );
        glavniPanelLayout.setVerticalGroup(
            glavniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(glavniPanelLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(prijavaTekst)
                .addGap(39, 39, 39)
                .addGroup(glavniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(upisImenaTekst)
                    .addComponent(unosImena_unos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(glavniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(glavniPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(glavniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(upisSifreTekst)
                            .addComponent(unosSifre_unos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(glavniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(smjenaTekst)
                            .addComponent(smjena_unos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(glavniPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(logo)))
                .addGap(38, 38, 38)
                .addGroup(glavniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prijaviSe_dugme, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetujPolja_dugme, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(249, Short.MAX_VALUE))
            .addGroup(glavniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(glavniPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(razdvaja, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(glavniPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(glavniPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleDescription("Caffe bar \"Romansa\" - Prijava");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unosSifre_unosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unosSifre_unosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unosSifre_unosActionPerformed
    
    int idUposlenika = 0;
    
    private void prijaviSe_dugmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prijaviSe_dugmeActionPerformed
        
        Connection konekcija = null;
        Statement stejtment = null;

        try{

            Class.forName("com.mysql.jdbc.Driver");
            System.out.println("Povezivanje sa databazom...");
            konekcija = DriverManager.getConnection(server_databaze,korisnik_databaze,sifra_databaze);
            String povlacenjeIzBaze = "Select * from uposlenici where uposlenik=? and sifra=?";
            PreparedStatement izvucenoIzBaze = konekcija.prepareStatement(povlacenjeIzBaze);
             
            izvucenoIzBaze.setString(1, unosImena_unos.getText());
            izvucenoIzBaze.setString(2, unosSifre_unos.getText());
            
            ResultSet rezultat = izvucenoIzBaze.executeQuery();
            
            if(rezultat.next()){
                
            idUposlenika = rezultat.getInt("id");
              
            String unosUBazu = "UPDATE uposlenici SET uposlenik=?, sifra=?, smjena=?, daLiJeLogovan=? where id="+idUposlenika;
            PreparedStatement ubacivanjeUBazu = konekcija.prepareStatement(unosUBazu);
            ubacivanjeUBazu.setString(1, unosImena_unos.getText());
            ubacivanjeUBazu.setString(2, unosSifre_unos.getText());
            ubacivanjeUBazu.setString(3, smjena_unos.getSelectedItem().toString());
            ubacivanjeUBazu.setString(4, "Da");
            
            ubacivanjeUBazu.executeUpdate();
           
                this.dispose();
                uspjesnaPrijavaProzor iskace = new uspjesnaPrijavaProzor();
                iskace.setVisible(true);
                
            }else{
                neuspjesnaPrijavaProzor iskace = new neuspjesnaPrijavaProzor();
                iskace.setVisible(true);
                unosImena_unos.setText("");
                unosSifre_unos.setText("");
                smjena_unos.setSelectedItem("Prva");
                
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Prijava.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Prijava.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_prijaviSe_dugmeActionPerformed

    private void resetujPolja_dugmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetujPolja_dugmeActionPerformed

        unosImena_unos.setText("");
        unosSifre_unos.setText("");
        smjena_unos.setSelectedItem("Prva");
        
    }//GEN-LAST:event_resetujPolja_dugmeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prijava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prijava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prijava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prijava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prijava().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel glavniPanel;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel prijavaTekst;
    private javax.swing.JButton prijaviSe_dugme;
    private javax.swing.JSeparator razdvaja;
    private javax.swing.JButton resetujPolja_dugme;
    private javax.swing.JLabel smjenaTekst;
    private javax.swing.JComboBox<String> smjena_unos;
    private javax.swing.JTextField unosImena_unos;
    private javax.swing.JPasswordField unosSifre_unos;
    private javax.swing.JLabel upisImenaTekst;
    private javax.swing.JLabel upisSifreTekst;
    // End of variables declaration//GEN-END:variables
}
