package Kasa;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Amar Musli, 2017/210017 - Fakultet za računarstvo i informatiku, Univerzitet Sinergija, Bijeljina.
 */
public class prikazRacuna extends javax.swing.JFrame {
    
   static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
   static final String server_databaze = "jdbc:mysql://192.168.10.16:3306/java"; 
   static final String korisnik_databaze = "student";
   static final String sifra_databaze = "student";


    /**
     * Creates new form Unos
     */
    public prikazRacuna() {
        initComponents();
        JFrame prikazRacuna = new JFrame();
        setLocationRelativeTo(null);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Kasa/slike/prijava.png")).getImage());
        prikazivanjeRacunaUTabeli();
       
    }
    
    public ArrayList<Racuni> prikazListeRacun() {
        
    ArrayList<Racuni> prikazListeRacuna = new ArrayList<>();
    
        Connection konekcija = null;
        Statement stejtment = null;

        try{

            Class.forName("com.mysql.jdbc.Driver");
            
            konekcija = DriverManager.getConnection(server_databaze,korisnik_databaze,sifra_databaze);
            String prikazivanjeIzBaze = "SELECT * FROM racuni";
            stejtment = konekcija.createStatement();
            ResultSet rezultat = stejtment.executeQuery(prikazivanjeIzBaze);
            Racuni RacuniPrikaz;
            while(rezultat.next()){
                RacuniPrikaz = new Racuni(rezultat.getString("brojracuna"),rezultat.getString("nazivfajla"),rezultat.getString("datum"),rezultat.getString("vrijeme"),rezultat.getString("radnik"),rezultat.getString("smjena"));
                prikazListeRacuna.add(RacuniPrikaz);
            }
            }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
      
     return prikazListeRacuna;   
    }
    
    public void prikazivanjeRacunaUTabeli(){
        
        ArrayList<Racuni> lista = prikazListeRacun();
        DefaultTableModel ispisUTabeli = (DefaultTableModel)tabelaRacuna.getModel();
        Object[] red = new Object[6];
        for(int i=0;i<lista.size(); i++){
            
            red[0] = lista.get(i).getBrojRacuna();
            red[1] = lista.get(i).getNazivFajla();
            red[2] = lista.get(i).getDatum();
            red[3] = lista.get(i).getVrijeme();
            red[4] = lista.get(i).getRadnik();
            red[5] = lista.get(i).getSmjena();
            ispisUTabeli.addRow(red);
            
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        glavniPanel = new javax.swing.JPanel();
        doSadaRacuniTekst = new javax.swing.JLabel();
        tabelaSkrol = new javax.swing.JScrollPane();
        tabelaRacuna = new javax.swing.JTable();
        otvoriRacun = new javax.swing.JButton();
        obrisiRacunIzBase = new javax.swing.JButton();
        ponovoUcitaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Caffe bar \"Romansa\" - Prikaz računa");
        setName("Caffe bar \"Romansa\" - Prikaz računa"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1037, 429));
        setResizable(false);
        setSize(new java.awt.Dimension(1037, 429));

        glavniPanel.setBackground(new java.awt.Color(27, 88, 138));
        glavniPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 120, 189), 3, true));
        glavniPanel.setToolTipText(null);
        glavniPanel.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        glavniPanel.setName("Caffe bar \"Romansa\" - Prikaz računa"); // NOI18N
        glavniPanel.setPreferredSize(new java.awt.Dimension(1037, 429));

        doSadaRacuniTekst.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        doSadaRacuniTekst.setForeground(new java.awt.Color(224, 220, 211));
        doSadaRacuniTekst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kasa/slike/listaracuna.png"))); // NOI18N
        doSadaRacuniTekst.setText("Ovdje možete pregledati do sada generisane račune");
        doSadaRacuniTekst.setToolTipText(null);
        doSadaRacuniTekst.setName("Caffe bar \"Romansa\" - Prikaz računa"); // NOI18N

        tabelaSkrol.setBackground(new java.awt.Color(27, 88, 138));
        tabelaSkrol.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 120, 189), 3, true));
        tabelaSkrol.setForeground(new java.awt.Color(224, 220, 211));
        tabelaSkrol.setToolTipText(null);
        tabelaSkrol.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        tabelaSkrol.setName("Caffe bar \"Romansa\" - Prikaz računa"); // NOI18N

        tabelaRacuna.setBackground(new java.awt.Color(27, 88, 138));
        tabelaRacuna.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 120, 189), 3, true));
        tabelaRacuna.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        tabelaRacuna.setForeground(new java.awt.Color(224, 220, 211));
        tabelaRacuna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Broj računa", "Naziv računa", "Datum", "Vrijeme", "Radnik koji je izdao račun", "Smjena radnika"
            }
        ));
        tabelaRacuna.setToolTipText(null);
        tabelaRacuna.setName("Caffe bar \"Romansa\" - Prikaz računa"); // NOI18N
        tabelaRacuna.setRowHeight(28);
        tabelaSkrol.setViewportView(tabelaRacuna);
        tabelaRacuna.getAccessibleContext().setAccessibleName("Caffe bar \"Romansa\" - Prikaz računa");
        tabelaRacuna.getAccessibleContext().setAccessibleDescription("Caffe bar \"Romansa\" - Prikaz računa");

        otvoriRacun.setBackground(new java.awt.Color(27, 88, 138));
        otvoriRacun.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        otvoriRacun.setForeground(new java.awt.Color(224, 220, 211));
        otvoriRacun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kasa/slike/predracun.png"))); // NOI18N
        otvoriRacun.setText("Otvori i pogledaj račun");
        otvoriRacun.setToolTipText(null);
        otvoriRacun.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 220, 211), 3, true));
        otvoriRacun.setName("Očisti polja"); // NOI18N
        otvoriRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otvoriRacunActionPerformed(evt);
            }
        });

        obrisiRacunIzBase.setBackground(new java.awt.Color(27, 88, 138));
        obrisiRacunIzBase.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        obrisiRacunIzBase.setForeground(new java.awt.Color(224, 220, 211));
        obrisiRacunIzBase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kasa/slike/obrisi.png"))); // NOI18N
        obrisiRacunIzBase.setText("Obriši račun iz baze");
        obrisiRacunIzBase.setToolTipText(null);
        obrisiRacunIzBase.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 220, 211), 3, true));
        obrisiRacunIzBase.setName("Očisti polja"); // NOI18N
        obrisiRacunIzBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obrisiRacunIzBaseActionPerformed(evt);
            }
        });

        ponovoUcitaj.setBackground(new java.awt.Color(27, 88, 138));
        ponovoUcitaj.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        ponovoUcitaj.setForeground(new java.awt.Color(224, 220, 211));
        ponovoUcitaj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kasa/slike/osvjezi.png"))); // NOI18N
        ponovoUcitaj.setText("Ponovo učitaj listu računa");
        ponovoUcitaj.setToolTipText(null);
        ponovoUcitaj.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 220, 211), 3, true));
        ponovoUcitaj.setName("Očisti polja"); // NOI18N
        ponovoUcitaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponovoUcitajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout glavniPanelLayout = new javax.swing.GroupLayout(glavniPanel);
        glavniPanel.setLayout(glavniPanelLayout);
        glavniPanelLayout.setHorizontalGroup(
            glavniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(glavniPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(glavniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(glavniPanelLayout.createSequentialGroup()
                        .addComponent(doSadaRacuniTekst)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(glavniPanelLayout.createSequentialGroup()
                        .addGroup(glavniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tabelaSkrol, javax.swing.GroupLayout.PREFERRED_SIZE, 939, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(glavniPanelLayout.createSequentialGroup()
                                .addComponent(otvoriRacun, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(obrisiRacunIzBase, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ponovoUcitaj, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 68, Short.MAX_VALUE))))
        );
        glavniPanelLayout.setVerticalGroup(
            glavniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(glavniPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(doSadaRacuniTekst)
                .addGap(46, 46, 46)
                .addComponent(tabelaSkrol, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(glavniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(otvoriRacun, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obrisiRacunIzBase, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ponovoUcitaj, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );

        doSadaRacuniTekst.getAccessibleContext().setAccessibleName("Caffe bar \"Romansa\" - Prikaz računa");
        doSadaRacuniTekst.getAccessibleContext().setAccessibleDescription("Caffe bar \"Romansa\" - Prikaz računa");
        tabelaSkrol.getAccessibleContext().setAccessibleName("Caffe bar \"Romansa\" - Prikaz računa");
        tabelaSkrol.getAccessibleContext().setAccessibleDescription("Caffe bar \"Romansa\" - Prikaz računa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(glavniPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(glavniPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        glavniPanel.getAccessibleContext().setAccessibleName("Caffe bar \"Romansa\" - Prikaz računa");
        glavniPanel.getAccessibleContext().setAccessibleDescription("Caffe bar \"Romansa\" - Prikaz računa");

        getAccessibleContext().setAccessibleDescription("Caffe bar \"Romansa\" - Prikaz računa");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void otvoriRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otvoriRacunActionPerformed

      TableModel pravljenjePredracuna = tabelaRacuna.getModel();
      
      int[] vrijednosti = tabelaRacuna.getSelectedRows();
      Object[] redovi = new Object[3];
      
      if(tabelaRacuna.getSelectionModel().isSelectionEmpty()){
          
            neuspjesnoDodavanjeNaRacun iskace = new neuspjesnoDodavanjeNaRacun();
            iskace.setVisible(true);
          
      }else{
      for(int i=0;i<vrijednosti.length; i++){
          
          
          redovi[0] = pravljenjePredracuna.getValueAt(vrijednosti[i], 0);
          
           if (Desktop.isDesktopSupported()) {
                    try {
                        File otvaranjeFajla = new File("Racun #" + redovi[0] + ".pdf");
                        Desktop.getDesktop().open(otvaranjeFajla);
                    } catch (IOException e) {
                        // ako ne bude moglo da se otvori
                    }
                }
          
          tabelaRacuna.getSelectionModel().clearSelection();
       
      }
      
      }

    }//GEN-LAST:event_otvoriRacunActionPerformed

    private void obrisiRacunIzBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obrisiRacunIzBaseActionPerformed
       
        Connection konekcija = null;
        Statement stejtment = null;

        try{

            Class.forName("com.mysql.jdbc.Driver");
            System.out.println("Povezivanje sa databazom...");
            konekcija = DriverManager.getConnection(server_databaze,korisnik_databaze,sifra_databaze);
            int red = tabelaRacuna.getSelectedRow();
            String pripremaZaBrisanje=(tabelaRacuna.getModel().getValueAt(red, 0).toString());
            String upitZaBrisanje = "Delete from racuni where brojracuna="+pripremaZaBrisanje;
            PreparedStatement brisanjeIzBase = konekcija.prepareStatement(upitZaBrisanje);
            brisanjeIzBase.executeUpdate();
            DefaultTableModel osvjezivanjeTabele = (DefaultTableModel)tabelaRacuna.getModel();
            osvjezivanjeTabele.setRowCount(0);
            prikazivanjeRacunaUTabeli();
           
             uspjesnoBrisanjeProzor iskace = new uspjesnoBrisanjeProzor();
             iskace.setVisible(true);

        } catch (Exception e) {
            
            neuspjesnoBrisanjeProzor iskace = new neuspjesnoBrisanjeProzor();
                iskace.setVisible(true);
            
        }  
        
    }//GEN-LAST:event_obrisiRacunIzBaseActionPerformed

    private void ponovoUcitajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ponovoUcitajActionPerformed
        
       DefaultTableModel osvjezivanjeTabele = (DefaultTableModel)tabelaRacuna.getModel();
       osvjezivanjeTabele.setRowCount(0);
       prikazivanjeRacunaUTabeli();
        
    }//GEN-LAST:event_ponovoUcitajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prikazRacuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prikazRacuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prikazRacuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prikazRacuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prikazRacuna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel doSadaRacuniTekst;
    private javax.swing.JPanel glavniPanel;
    private javax.swing.JButton obrisiRacunIzBase;
    private javax.swing.JButton otvoriRacun;
    private javax.swing.JButton ponovoUcitaj;
    private javax.swing.JTable tabelaRacuna;
    private javax.swing.JScrollPane tabelaSkrol;
    // End of variables declaration//GEN-END:variables

}