package Kasa;

import javax.swing.JFrame;

/**
 *
 * @author Amar Musli, 2017/210017 - Fakultet za računarstvo i informatiku, Univerzitet Sinergija, Bijeljina.
 */
public class uspjesnaPrijavaProzor extends javax.swing.JFrame {

    /**
     * Creates new form uspjesnaPrijavaProzor
     */
    public uspjesnaPrijavaProzor() {
        initComponents();
        JFrame uspjesnaPrijavaProzor = new JFrame();
        setLocationRelativeTo(null);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Kasa/slike/prijava.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        glavniPanel = new javax.swing.JPanel();
        uspjesnaPrijavaTekst = new javax.swing.JLabel();
        ureduDugme = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bravo!");
        setBackground(new java.awt.Color(27, 88, 138));
        setName("Uspješno ste se prijavili!"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        glavniPanel.setBackground(new java.awt.Color(27, 88, 138));
        glavniPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 120, 189), 6));
        glavniPanel.setToolTipText(null);
        glavniPanel.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        glavniPanel.setName("Uspješno ste se prijavili!"); // NOI18N

        uspjesnaPrijavaTekst.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        uspjesnaPrijavaTekst.setForeground(new java.awt.Color(224, 220, 211));
        uspjesnaPrijavaTekst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kasa/slike/uspjesno.png"))); // NOI18N
        uspjesnaPrijavaTekst.setText("Uspješno ste se prijavili!");
        uspjesnaPrijavaTekst.setToolTipText(null);
        uspjesnaPrijavaTekst.setName("Uspješno ste se prijavili!"); // NOI18N

        ureduDugme.setBackground(new java.awt.Color(27, 88, 138));
        ureduDugme.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        ureduDugme.setForeground(new java.awt.Color(224, 220, 211));
        ureduDugme.setText("  U redu  ");
        ureduDugme.setToolTipText(null);
        ureduDugme.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 220, 211), 3, true));
        ureduDugme.setName("U redu"); // NOI18N
        ureduDugme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ureduDugmeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout glavniPanelLayout = new javax.swing.GroupLayout(glavniPanel);
        glavniPanel.setLayout(glavniPanelLayout);
        glavniPanelLayout.setHorizontalGroup(
            glavniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, glavniPanelLayout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addComponent(ureduDugme, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
            .addGroup(glavniPanelLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(uspjesnaPrijavaTekst)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        glavniPanelLayout.setVerticalGroup(
            glavniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(glavniPanelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(uspjesnaPrijavaTekst)
                .addGap(35, 35, 35)
                .addComponent(ureduDugme, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        uspjesnaPrijavaTekst.getAccessibleContext().setAccessibleDescription("Uspješno ste se prijavili!");
        ureduDugme.getAccessibleContext().setAccessibleDescription("U redu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(glavniPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(glavniPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        glavniPanel.getAccessibleContext().setAccessibleName("Uspješno ste se prijavili!");
        glavniPanel.getAccessibleContext().setAccessibleDescription("Uspješno ste se prijavili!");

        getAccessibleContext().setAccessibleName("Uspješno ste se prijavili!");
        getAccessibleContext().setAccessibleDescription("Uspješno ste se prijavili!");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ureduDugmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ureduDugmeActionPerformed
        
            this.dispose();
            Kasa iskace = new Kasa();
            iskace.setVisible(true);
               
    }//GEN-LAST:event_ureduDugmeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uspjesnaPrijavaProzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uspjesnaPrijavaProzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uspjesnaPrijavaProzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uspjesnaPrijavaProzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new uspjesnaPrijavaProzor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel glavniPanel;
    private javax.swing.JButton ureduDugme;
    private javax.swing.JLabel uspjesnaPrijavaTekst;
    // End of variables declaration//GEN-END:variables
}
